### ISSUE TITLE
SCEE 59.0-alpha1 keeps crashing immediately after selecting one of the overlays

### ISSUE THREAD

**Issue by mcliquid** [Helium314/StreetComplete#609]
**How to Reproduce**
I've used the newest SCEE 59.0-alpha1 version already some times yesterday but today the first time I've used the Shops-Overlay.
Steps I've did:
1. Open the app
2. Go to an area
3. Download the data manually
4. Select the Shops-Overlay
5. App crashed once
6. Try to restart via App Icon: App crashes **every** time

**Expected Behavior**
Download Data manually and use the Shops-Overlay.

**Does it happen in normal StreetComplete?**
No

**Versions affected**
SCEE 59.0-alpha1 on Android 14

<details>
  <summary>Stack trace:</summary>

(Log is too long for GitHub - I can provide it via Mail)

```

java.lang.IllegalArgumentException: bad color string: #fff
at de.westnordost.streetcomplete.util.ktx.ColorKt.toRGB(Color.kt:45)
at de.westnordost.streetcomplete.screens.main.map.components.StyleableOverlayMapComponent.getDarkenedColor(StyleableOverlayMapComponent.kt:381)
at de.westnordost.streetcomplete.screens.main.map.components.StyleableOverlayMapComponent.toFeatures(StyleableOverlayMapComponent.kt:258)
at de.westnordost.streetcomplete.screens.main.map.components.StyleableOverlayMapComponent.set(StyleableOverlayMapComponent.kt:226)
at de.westnordost.streetcomplete.screens.main.map.components.StyleableOverlayMapComponent$set$1.invokeSuspend(StyleableOverlayMapComponent.kt:0)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:104)
at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:584)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:811)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:715)
at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:702)
Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@1875330, Dispatchers.Default]
```
</details>

**Comment by mic140** [comment]
I had the same thing when selecting the address layer

**Comment by TomTurnschuh** [comment]
And I just experienced the same after activating the road surface overlay.

```
java.lang.IllegalMonitorStateException
	at java.util.concurrent.locks.ReentrantLock$Sync.tryRelease(ReentrantLock.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.release(AbstractQueuedSynchronizer.java:1007)
	at java.util.concurrent.locks.ReentrantLock.unlock(ReentrantLock.java:494)
	at org.maplibre.android.storage.FileSource.unlockPathLoaders(FileSource.java:367)
	at org.maplibre.android.storage.FileSource.access$100(FileSource.java:31)
	at org.maplibre.android.storage.FileSource$FileDirsPathsTask.onPostExecute(FileSource.java:224)
	at org.maplibre.android.storage.FileSource$FileDirsPathsTask.onPostExecute(FileSource.java:204)
	at android.os.AsyncTask.finish(AsyncTask.java:771)
	at android.os.AsyncTask.-$$Nest$mfinish(Unknown Source:0)
	at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:788)
	at android.os.Handler.dispatchMessage(Handler.java:107)
	at android.os.Looper.loopOnce(Looper.java:232)
	at android.os.Looper.loop(Looper.java:317)
	at android.app.ActivityThread.main(ActivityThread.java:8623)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ExecInit.main(ExecInit.java:50)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:369)
```

**Comment by Helium314** [comment]
@TomTurnschuh that's unrelated, see https://github.com/maplibre/maplibre-native/issues/2432
